version: "3.7"

services:
    naurandir-discord-clem:
        image: naurandir/discord-clem:latest
        container_name: naurandir-discord-clem
        volumes:
            - ./log:/home/appuser/log
        networks:
            - naurandir_bridge
        deploy:
            resources:
                limits:
                    memory: 400M
                reservations:
                    memory: 300M

networks:
  naurandir_bridge:
    external:
      name: naurandir_bridge